### ISSUE TITLE
Plotting issue

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#11]
After plotting done, repeated messages appear in the console:
Error in fetch(key) : 
  lazy-load database '/home/chad/R/x86_64-pc-linux-gnu-library/3.3/sensemakr/help/sensemakr.rdb' is corrupt

These continue even after dev.off()

**Comment by statsccpr** [comment]
i would get that error sometimes between old to new version installs,

try using the force=TRUE arg in install_github and then restarting the r session.

that might fix it

On Aug 11, 2017 5:59 PM, Chad Hazlett <notifications@github.com> wrote:

After plotting done, repeated messages appear in the console:
Error in fetch(key) :
lazy-load database '/home/chad/R/x86_64-pc-linux-gnu-library/3.3/sensemakr/help/sensemakr.rdb' is corrupt

These continue even after dev.off()

**Comment by statsccpr** [comment]
Does this still occur?

I get it usually after forcing another install thru install_github(force=TRUE)

but restarting the R session after resolves it for me
