### ISSUE TITLE
Class name sensemakr vs. sensemade

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#12]
We have class(sensemade) at the moment. While cute, for a new user there is an expectation that the class will be the package name, and I think we should adhere to that.

**Comment by statsccpr** [comment]
done in 

https://github.com/chadhazlett/sensemakr/commit/da0cbe0b0a98572e51c6cd076b13837be7012984

and

https://github.com/chadhazlett/sensemakr/commit/5ef93fb866572ccad3c5a973c2b80b726349a680
