### ISSUE TITLE
worstcaseplot defaults

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#13]
worstcaseplot, if called directly, fails when no default limit is given:

> worstcaseplot(sense.out)
Error in seq.default(0, lim, by = 0.001) : 
  'to' cannot be NA, NaN or infinite
In addition: Warning message:
In max(r2d, na.rm = TRUE) : no non-missing arguments to max; returning -Inf

**Comment by statsccpr** [comment]
temporary fix is to not export the specific plot methods

neither worstcaseplot() nor contourplot()

as in the commit below

https://github.com/chadhazlett/sensemakr/commit/fe03bfa553944104e62fad3e699cc91fd6752710

**Comment by chadhazlett** [comment]
Yes; I've already committed this change.

**Comment by statsccpr** [comment]
confirmed, pulled the new changes
