### ISSUE TITLE
sense.out$benchmark output

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#16]
Let's remove the column "covariate" from the output -- it's redundant with the row names, and as a character it prevents easy manipulation of the rest of the matrix.

**Comment by statsccpr** [comment]
done in 

https://github.com/chadhazlett/sensemakr/commit/d483839b3d7bb08c1928f53a01de731ffdcf2c26

downstream changes in vignette in
https://github.com/chadhazlett/sensemakr/commit/3e74e046ee7038001684be5507019de89eb46e04
