### ISSUE TITLE
full report? (not urgent)

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#2]
Idea: a function such as fullreport(obj, filename) that produces a pdf with all the plot types and the natural language interpretation. We could even add there various warning and caveats such as "whether this is strong evidence for the credibility of your result depnds on whether you feel variables such as [varname] are likely to be more powerful confounders than any unobservable, which depends on ...".

**Comment by carloscinelli** [comment]
Yeah, after we have all the tables and plot functions working this would be good. It could be both pdf or html, with html one can see the results directly on RStudio. A small shiny app would be good too.
