### ISSUE TITLE
Spot check on interpret printout

### ISSUE THREAD

**Issue by statsccpr** [carloscinelli/sensemakr#27]
In the vignette
https://github.com/chadhazlett/sensemakr/blob/master/vignettes/sensemakr.md

*edit* the worstcaseinterpret() matches graphic of worstcaseplot() one parameter is x axis and other parameter is curve type

@chadhazlett 

The two different non-symmetric sentence structures is intended right? Along with 'two dimensions', intended to provide users with two grammatical variants?

Result of `interpret`

```
## 
## ### Benchmarking ###
## 
## ---Using the covariate most strongly associated with the treatment assignment as a benchmark---
## 
## An unobserved confounder explaining as much of the treatment as 'female' (0.009)  would be able 
to cause at most a bias of 0.062 with an adjusted treatment effect of 0.035 in the extreme case where 
the confouder explains all the residual variance of the outcome (R2y = 1).
## 
## ---Using the covariate most strongly associated with the outcome as a benchmark---
## 
## An unobserved confounder as associated with the outcome as 'female' (R2y = 0.109)  would have to 
be at least 18.7 times as strongly associated with the treatment (reaching R2d = 0.17) in order to reduce 
the treatment effect by 100%
```

**Comment by chadhazlett** [comment]
Some of my changes to the language seem to have been lost. I can revise and
then let's see what everybody thinks.
