### ISSUE TITLE
Possible to save plot?

### ISSUE THREAD

**Issue by wicai** [carloscinelli/sensemakr#46]
Hi,

I'm having some trouble saving the plots made by sensemakr.  
For example, if I run

plot(sensitivity)

it gives a plot to my output, but neither 

pdf("plots.pdf", width=6, height=3)
plot(sensitivity)
dev.off()

nor ggsave() works to save the plot.  

I also tried storing the plot as https://stackoverflow.com/questions/29583849/save-a-plot-in-an-object but this doesn't seem to work with your package. 

What's the right way to do this?

Thanks,
Will

**Comment by carloscinelli** [comment]
Hi wicai , the code you sent worked fine for me here.

Maybe you should try running dev.off() a couple times before running the plot again, to make sure there is nothing else going on? Could you test that and see how it goes?

On a side note, the current plot defaults of the github version works best with width = 6 and height = 4. 

Best, Carlos

**Comment by wicai** [comment]
Ah turns out there's some weirdness in running r notebooks and capturing plots.  Sorry about that, and thanks for developing this methodology!

**Comment by carloscinelli** [comment]
Thanks wicai, any other problems or question, please let us know!
