### ISSUE TITLE
How to manually provide data for benchmark covariates?

### ISSUE THREAD

**Issue by sharifamlani** [carloscinelli/sensemakr#48]
My model requires me to adjust for cluster standard errors. I use the `coeftest` function in R to do this. Unfortunately, the object created by the `coeftest` function is not compatible with the model argument in `sensemakr`. Thankfully, the estimate, se, and dof can be inputted manually into the `sensemakr` function.

However, I do not see a way to input the benchmark covariates manually? How can I input the benchmark covariates manually into the `sensemakr` function?

**Comment by carloscinelli** [comment]
Hi Sharif, I answered by e-mail but will also include the answer here for future reference.

For the benchmark covariate Xj, you will need to provide the partial R2 of Xj  both with the treatment D and the outcome Y. 

That is, there are two arguments:

- For the argument r2dxj.x you will provide the partial R2 of the benchmark covariate Xj with the treatment D.  You can compute that with the function partial_r2 using a regression of the treatment on the covariates (or using directly the t-value and degrees of freedom).

- For the argument r2yxj.dx you will provide the partial R2 of the benchmark covariate Xj with the outcome Y.  You can compute that with the function partial_r2 using a regression of the outcome on the treatment and the covariates (or using directly the t-value and degrees of freedom).

You can see an example of how to do that in the software paper, page 18.
