### ISSUE TITLE
Sensitivity analysis for Generalized Random Forest (GRF) or SuperLearner

### ISSUE THREAD

**Issue by adeldaoud** [carloscinelli/sensemakr#51]
Hi

I how one could conduct sensitivity analysis using sensemakr based on machine learning algorithm for causal inference, in particular the GRF or SuperLearner?

I see that the sensemakr function takes the estimate and SE, but it also requires the degrees of freedom (dF). In ML setting (for non-parametric models), it is unclear what dF is.

Your input is most appriciated

**Comment by carloscinelli** [comment]
Hi @adeldaoud we have recent theoretical results that covers sensitivity for the ATE using machine learning models, see here: https://arxiv.org/abs/2112.13398

**Comment by adeldaoud** [comment]
@carloscinelli ok, that sounds great. Is there a time plan for when approximately the package will be available?

**Comment by carloscinelli** [comment]
Hi @adeldaoud under construction but checkout https://github.com/carloscinelli/dml.sensemakr

**Comment by adeldaoud** [comment]
@carloscinelli thanks for letting me know, and great work! I will take a look, and report back in case needed.

**Comment by carloscinelli** [comment]
Available at: https://github.com/carloscinelli/dml.sensemakr
